repos:
- repo: local
  hooks:
  - id: commit-lint
    name: commit-lint
    language: node
    entry: commitlint -f
    stages: [commit-msg]
    pass_filenames: false
    additional_dependencies:
    - '@commitlint/cli'
    - '@commitlint/config-conventional'
