[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/cobra"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/viper"
  branch = "master"

[[constraint]]
  name = "k8s.io/client-go"
  version = "v6.0.0"

[[constraint]]
  name = "go.uber.org/zap"
  branch = "master"

[[override]]
  name = "github.com/golang/glog"
  source = "github.com/istio/glog"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
